# --------------
# File locations
# --------------

# Note: the location of the Wikimedia login credentials is hard-coded to be the file "commons_credentials.txt"
# located in the user's home directory. This can be changed, but if so you must take care to isolate
# that file from the code and configuration files if they are publicly exposed (e.g. on GitHub).

# Controls whether some paths are relative to the home directory or not. 
# If not, they may be absolute or relative to the current working directory.
path_is_relative_to_home_directory: true
local_image_directory_path: gallery_digital_image_archive/ # location of images to upload to Commons

# Absolute file paths for IIIF server upload
local_image_root_directory: /users/baskausj/gallery_digital_image_archive/
tiff_image_root_directory: /users/baskausj/gallery_pyramidal_tiffs/

# File locations in AWS S3
s3_iiif_bucket_name: iiif-library-cantaloupe-storage
s3_manifest_bucket_name: iiif-manifest.library.vanderbilt.edu
s3_iiif_project_directory: gallery

# Root URLs for IIIF-related files
iiif_server_url_root: https://iiif.library.vanderbilt.edu/iiif/3/
manifest_iri_root: https://iiif-manifest.library.vanderbilt.edu/


# --------
# Behavior
# --------

# Controls whether the newly created Commons media page opens in a new browser window. 
# Useful when testing on a few images, but may be annoying if uploading many media items.
open_browser_tab_after_upload: true


# ---------------------------
# Institutional customization
# ---------------------------

# Currently only affects language tag designation for the caption fir structured data on Commons
default_language: en

# This supposedly causes a GLAM institution's Institution: template to be transcluded as an infobox
# into Artwork and Art Photo file description pages. Leave blank to omit.
# Example https://commons.wikimedia.org/wiki/Institution:Vanderbilt_University_Fine_Arts_Gallery
# As of 2022-08-21, it doesn't seem to be working. 
templated_institution: Vanderbilt University Fine Arts Gallery

# The name of the institution to be inserted between the descriptive text and the local filename to form
# the Commons filename. Example: 
# Four Studies of a Draped Torso - Vanderbilt Fine Arts Gallery - 1973.016.med.jpg
filename_institution: Vanderbilt Fine Arts Gallery

# Commons categories to be added to the images.
category_strings:
  - Vanderbilt University Fine Arts Gallery


# -----------------------------------
# Copyright and license configuration
# -----------------------------------

# Page wikitext templates

# NOTE: The PD-old-100-expired tag provides notices for both US: more than 95 years (Q47246828)
# and countries where copyright expires 100 or fewer years after author's death (Q29940705)
# It's used here because all works to be posted from the Vanderbilt Fine Arts Gallery are
# covered in one or the other of these categories. However, the called function allows other reasons
# that could vary from work to work and would require modification of this value.
artwork_license_text_3d: PD-old-100-expired

# Refer to https://commons.wikimedia.org/wiki/Commons:Licensing#License_information
# https://commons.wikimedia.org/wiki/Commons:Credit_line#Creative_Commons
# and https://commons.wikimedia.org/wiki/Template:Cc-by-4.0
photo_license_text_3d: Cc-by-4.0 |1=photo © [https://www.vanderbilt.edu/ Vanderbilt University] / [https://www.library.vanderbilt.edu/gallery/ Fine Arts Gallery] / [https://creativecommons.org/licenses/by/4.0/ CC BY 4.0]

# The PD-Art tag provides the justification for saying that the photo isn't covered by copyright.
# See the note above about PD-old-100-expired.
artwork_license_text_2d: PD-Art|PD-old-100-expired

# Structured data on Commons (SDC) values

# Note that SDC values apply to the media item and not the underlying artwork. Licensing information for the
# artwork is given on the Wikidata page for the artwork. So these values are only used for photos of 3D artwork
# since 2D artwork is considered to lack creative input and therefore not be copyrightable.

# Copyright status of photograph of a 3D work, value for P6216
# copyrighted (Q50423863) or 
# copyrighted, dedicated to the public domain by copyright holder (Q88088423, use with CC0),
# or public domain (Q19652, needs qualifier for why it's in the public domain)
photo_copyright_qid: Q50423863

# License of copyrighted photo, value for P275
# Typically a Creative Commons License, for example CC BY (Q6905323)
photo_license_qid: Q6905323

# For photographer structured data
photographer_of_work: Q29052 # Vanderbilt University


# ----------------------------------------------------------------------
# Screening criteria
# ----------------------------------------------------------------------

public_domain_categories:
  - artist died before copyright cutoff
  - artist was born before 1800
  - assessed to be out of copyright
  - from style or period that ended prior to copyright cutoff
  - inception prior to copyright cutoff
copyright_cutoff_date: 1926

# size_filter options are pixsquared or filesize (filetype not yet implemented)
size_filter: pixsquared
minimum_filesize: 1000 # minimum filesize in kilobytes, only used for filesize filter
minimum_pixel_squared: 1000000 # minimum (pixelWidth x pixelHeight) value, only used for pixsquared filter
requrired_filetype: tiff # required filetype, only used for filetype filter (not yet implemented)


# ----------------------------------------------------------------------
# DO NOT MESS WITH VALUES BELOW THIS UNLESS YOU KNOW WHAT YOU ARE DOING!
# ----------------------------------------------------------------------

# Non-critical edits to commons should be made no faster than once every 5 seconds. 
# See https://commons.wikimedia.org/wiki/Commons:Bots#Bot_speed

# IMPORTANT NOTE: If you hack this script to upload media to Commons, you MUST NOT decrease the delay time between
# API writes to less than 5 seconds in order to speed up writing. If you do, then your script isn't 
# BaskaufCommonsBot and you need to change the user_agent_string_template to use your own URL and email address.
# The same holds true if you make other substantive changes to the way that the script interacts with the API.
# This script attempts to respect the "good citizen" guidelines for using the API and you should too.

# Because of the ASW s3 bucket upload, which is slow, I'm not using a 5 second delay here. This short delay
# just gives a short break between the end of the media upload and uploading the structured data. There will
# be a long delay after the structured data upload and when the next media upload begins because of the 
# intervening s3 upload. If you hack this script and don't have an action that includes a built-in delay,
# you should set this sleeptime to something like the 5 second commons_sleep value.
commons_upload_sleep_time: 0.5

# Set the value of the maxlag parameter to back off when the Commons API server is lagged.
# This applies only to uploads to the structured data on Commons Wikibase instance.
# see https://www.mediawiki.org/wiki/Manual:Maxlag_parameter
# The recommended value is 5 seconds.
# To not use maxlang, set the value to 0
# To test the maxlag handler code, set maxlag to a very low number like .1
# If you don't know what you are doing, leave this value alone. In any case, it is rude to use a value greater than 5.
maxlag: 5

# commons_sleep is used to determine waiting time when writing structured data and the API is lagged.
commons_sleep: 5

# If you change these values or significantly modify the software, you need to use your own user-agent string.
# %s will be replaced with the current script_version value from the script global variables.
user_agent_string_template: BaskaufCommonsBot/%s (https://github.com/HeardLibrary/linked-data/tree/master/commonsbot; mailto:steve.baskauf@vanderbilt.edu)
