constants:
  # Globally suppress use of series ordinal. Will always be suppressed if only one author.
  # Typically should be false unless data source has unordered agents.
  suppress_series_ordinal: false

# mapping_function is the name of a function that calculates the value based on the value in the source column
# in_col_label is the column in the source table that's passed into the function. 
sources:
- out_col_label: author
  mapping_function: extract_names_from_list
  in_col_label: Author
  use_settings: True
- out_col_label: editor
  mapping_function: extract_names_from_list
  in_col_label: Editor
  use_settings: True
- out_col_label: translator
  mapping_function: extract_names_from_list
  in_col_label: Translator
  use_settings: True
ref:
- out_col_label: referenceUrl
  mapping_function: set_reference
  in_col_label: Url
  reference_dfs: 
  - full_works
- out_col_label: stated_in
  mapping_function: set_stated_in
  in_col_label: Url
  reference_dfs: 
  - full_works
