data_path: ''
item_pattern_file: graph_pattern.txt
item_source_csv: ''
outfiles:
- output_file_name: articles.csv
  label_description_language_list:
  - en
  manage_descriptions: true
  prop_list:
  - variable: instance_of
    value_type: item
    pid: P31
    qual: []
    ref:
    - variable: referenceUrl
      value_type: uri
      pid: P854
    - variable: retrieved
      value_type: date
      pid: P813
  - variable: country
    value_type: item
    pid: P17
    qual: []
    ref:
    - variable: referenceUrl
      value_type: uri
      pid: P854
    - variable: retrieved
      value_type: date
      pid: P813
  - variable: location
    value_type: item
    pid: P276
    qual: []
    ref:
    - variable: referenceUrl
      value_type: uri
      pid: P854
    - variable: retrieved
      value_type: date
      pid: P813
  - variable: title_en
    value_type: monolingualtext
    language: en
    pid: P1476
    qual: []
    ref:
    - variable: referenceUrl
      value_type: uri
      pid: P854
    - variable: retrieved
      value_type: date
      pid: P813
  - variable: start_time
    value_type: date
    pid: P580
    qual: []
    ref:
    - variable: referenceUrl
      value_type: uri
      pid: P854
    - variable: retrieved
      value_type: date
      pid: P813
  - variable: end_time
    value_type: date
    pid: P582
    qual: []
    ref:
    - variable: referenceUrl
      value_type: uri
      pid: P854
    - variable: retrieved
      value_type: date
      pid: P813
  - variable: described_at
    value_type: uri
    pid: P973
    qual:
    - variable: lang_of_work
      value_type: item
      pid: P407
    ref:
    - variable: referenceUrl
      value_type: uri
      pid: P854
    - variable: retrieved
      value_type: date
      pid: P813
- output_file_name: exhibited_creators.csv
  label_description_language_list: []
  manage_descriptions: false
  prop_list:
  - variable: exhibited_creator
    value_type: item
    pid: P10661
    qual: []
    ref:
    - variable: referenceUrl
      value_type: uri
      pid: P854
    - variable: retrieved
      value_type: date
      pid: P813
