# Version information
script_version: 0.1.0

# Default language used for labels and descriptions
default_language: en

# User-Agent information. 
# The user_agent string identifies this application to Wikimedia APIs,
# so if you make significant modifications to the script or configuration that would change
# the way that it operaties, you need to change this to your email address. 
operator_email_address: steve.baskauf@vanderbilt.edu

# Settings for suppressing various checks.
# These setting should all be set to true under normal operations.
check_for_previous_processing: true
skip_if_containing_work_not_found: true
skip_if_not_known_type: true
skip_if_no_author_information: true
check_if_work_in_wikidata: true
divert_possible_partial_titles: true # only evaluated if check_if_work_in_wikidata is true

# Settings for language detection. 
language_precision_cutoff: 0.95 # above this level automatically assigned, below issues a warning

# Settings for matching work titles to existing Wikidata item labels (empiracally determined)
existing_work_fuzzy_match_cutoff: 97 # above this level no errors in testing, automatically assigned
# The subtitle cutoff probably caught all partial title/subtitle cases.
# But there were also errors with the same scores as some correct ones, so they need human review.
existing_work_subtitle_fuzzy_match_cutoff: 86

# Settings for communicating with the Wikidata API
sparql_sleep: 0.1 # minimal delay between SPARQL queries in seconds

# Settings for names extraction (from Zotero export)
names_separator: ; # used to separate names on a concatenated list
name_part_separator: "," # used to separate surname and given names (reversed)

# File settings
data_file_path: data/
source_data_filename: book_chapters_to_upload.csv
reference_file_path: ref/
log_path: logs/
temporary_files_path: temp/
configuration_files_path: config/

# Wikidata language codes used when the language of a work is inferred from title language detection
language_qid:
  en: Q1860
  de: Q188
  fr: Q150
  es: Q1321
  it: Q652
  nl: Q7411
  zh: Q7850
  no: Q9043
  ar: Q13955
  he: Q9288
  pt: Q5146

language_lingua_names:
  ENGLISH: en
  FRENCH: fr
  GERMAN: de
  SPANISH: es
  ITALIAN: it
  DUTCH: nl
  CHINESE: zh
  NYNORSK: no
  ARABIC: ar
  HEBREW: he
  PORTUGUESE: pt

# List of known work types used by Zotero
work_types:
- type_string: journalArticle
  qid:        Q18918145 # academic journal article, alternatively Q13442814 scholarly article
  description: journal article
  equivalent_types: ['Q18918145', 'Q13442814', 'Q191067', 'Q7318358', 'Q637866'] # academic journal article, scholarly article, article, review article, book review
- type_string: book
  qid:         Q3331189 # "version, edition, or translation"
  description: book
  equivalent_types: ['Q3331189', 'Q571', 'Q193495', 'Q193495'] # version/edition/translation, book, monograph, edited volume
- type_string: bookSection
  qid:         Q21481766 # "academic chapter"
  description: academic book chapter
  equivalent_types: ['Q21481766']
- type_string: thesis
  qid:         Q1266946 # "thesis"
  description: thesis
  equivalent_types: ['Q1266946']
- type_string: encyclopediaArticle
  qid:         Q13433827 # "encyclopedia article"
  description: encyclopedia article
  equivalent_types: ['Q13433827']
- type_string: dictionaryEntry
  qid:         Q1580166 # "dictionary entry"
  description: dictionary entry
  equivalent_types: ['Q1580166']
- type_string: conferencePaper
  qid:         Q23927052 # "conference paper"
  description: conference paper
  equivalent_types: ['Q23927052']

# List of work types that are contained by other works
contained_types:
#- Q23927052 # conference paper should be here, but we don't want to suppress uploads of it so leave off for now
- Q18918145 # "academic journal article"
- Q21481766 # "academic chapter"
- Q13433827 # "encyclopedia article"
- Q1580166 # "dictionary entry"

